package org.universaltranslator.core;

/** Cheap offline checks used to avoid unnecessary network requests. */
public final class LanguageHeuristics {
    /**
     * Every name the mod uses for itself: the three locales shipped in
     * {@code assets/universal_translator/lang/} plus the project's former name.
     *
     * <p>The mod's own chat and status messages are built from
     * {@code message.universal_translator.*} and always contain this name, so the name is the
     * part that identifies them. Matching the name instead of the bracketed form matters
     * because only some locales wrap it: {@code "MC 自动翻译工具：切换失败"} and
     * {@code "MC 自動翻譯工具：切換失敗"} carry no brackets at all, and the Traditional Chinese
     * name is a different string from the Simplified one that the old literal list hard-coded.
     * The separator and the optional {@code §}-formatting around the name are ignored, so the
     * check does not depend on the active language file.
     */
    private static final String[] SELF_NAMES = {
            "MC Auto Translation Tool",
            "MC 自动翻译工具",
            "MC 自動翻譯工具",
            "Universal Translator"
    };

    private LanguageHeuristics() {
    }

    public static boolean shouldTranslate(String text, String targetLanguage) {
        if (text == null || text.trim().isEmpty()) {
            return false;
        }
        // Messages generated by the mod itself are already localized and must remain stable.
        if (containsSelfName(text)) {
            return false;
        }
        if (TranslationOutputValidator.containsInternalArtifact(text)) {
            return false;
        }

        int letters = 0;
        int han = 0;
        for (int i = 0; i < text.length(); i++) {
            char value = text.charAt(i);
            if (Character.isLetter(value)) {
                letters++;
                Character.UnicodeBlock block = Character.UnicodeBlock.of(value);
                if (block == Character.UnicodeBlock.CJK_UNIFIED_IDEOGRAPHS
                        || block == Character.UnicodeBlock.CJK_UNIFIED_IDEOGRAPHS_EXTENSION_A
                        || block == Character.UnicodeBlock.CJK_COMPATIBILITY_IDEOGRAPHS) {
                    han++;
                }
            }
        }

        if (letters == 0) {
            return false;
        }
        // Mixed Chinese/Latin labels still need their Latin portion translated. Existing Han
        // runs are protected later, so skip only when every detected letter is already Han.
        if (isChineseTarget(targetLanguage) && han == letters) {
            return false;
        }
        return true;
    }

    /**
     * True when the text is one of the mod's own messages. Locale independent in the sense that
     * it never depends on the brackets or the separator a language file chose, only on the mod's
     * display name being present. Kept allocation free because it runs on the render thread.
     */
    private static boolean containsSelfName(String text) {
        for (String selfName : SELF_NAMES) {
            if (text.contains(selfName)) {
                return true;
            }
        }
        return false;
    }

    private static boolean isChineseTarget(String language) {
        if (language == null) {
            return false;
        }
        String normalized = language.toLowerCase().replace('_', '-');
        return normalized.equals("zh") || normalized.startsWith("zh-");
    }
}
